language: php

php:
- '7.2'

stages:
- test
- name: deploy
  if: branch = msqur.com

branches:
  only:
  - master
  - msqur.com

jobs:
  include:
  - stage: test
    script: phpunit tests
  - stage: deploy
    script: bash deploy.sh
