language: php

php:
- '7.2'

stages:
- test

jobs:
  include:
  - stage: test
    script: phpunit tests

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: msqur.com
    condition: $TRAVIS_TAG =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
