name: Unit Tests

on:
  push:
   branches:
     - prod
  pull_request:
   branches:
     - prod

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update and install PHP 7.3
      run: |
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install php7.3
